package com.example.data

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class GenerateContentRequest(
    val contents: List<Content>,
    val generationConfig: GenerationConfig? = null,
    val systemInstruction: Content? = null
)

@JsonClass(generateAdapter = true)
data class Content(
    val parts: List<Part>
)

@JsonClass(generateAdapter = true)
data class Part(
    val text: String? = null
)

@JsonClass(generateAdapter = true)
data class GenerationConfig(
    val responseMimeType: String? = null,
    val temperature: Float? = null,
    val topP: Float? = null,
    val topK: Int? = null
)

@JsonClass(generateAdapter = true)
data class GenerateContentResponse(
    val candidates: List<Candidate>?
)

@JsonClass(generateAdapter = true)
data class Candidate(
    val content: Content?
)

// Structured Lesson Data Models generated by Gemini
@JsonClass(generateAdapter = true)
data class LessonJson(
    val title: String,
    val introduction: String,
    val coreConcepts: List<String>,
    val lessonText: String,
    val practicalAssignment: String,
    val quiz: List<QuizQuestionJson>
)

@JsonClass(generateAdapter = true)
data class QuizQuestionJson(
    val question: String,
    val options: List<String>,
    val correctOptionIndex: Int,
    val explanation: String
)
